import Goldbach.OffDiagonalCertificate.FullSupportWindow

open Goldbach.OffDiagonalCertificate

#check Goldbach.OffDiagonalCertificate.pairDisplacement_eq_zero_iff
#check Goldbach.OffDiagonalCertificate.weight_eq_positivePart_sub_negativePart
#check Goldbach.OffDiagonalCertificate.mod3SignedImbalance_pos_iff_negativeMass_lt_positiveMass
#check Goldbach.OffDiagonalCertificate.intrinsicFavorableCore_eq_mod3PositiveMass_of_all_mem_window
#check Goldbach.OffDiagonalCertificate.displacement_abs_lt_target_of_mem_of_even
#check Goldbach.OffDiagonalCertificate.fixedP3_M2_all_displacements_mem_window_of_even
#check Goldbach.OffDiagonalCertificate.fixedP3_M2_intrinsicCore_eq_mod3PositiveMass_of_even
#check Goldbach.OffDiagonalCertificate.fixedP3_M2_negativeMass_lt_intrinsicCore_of_ge56_even_of_signedImbalance_pos

#print axioms Goldbach.OffDiagonalCertificate.pairDisplacement_eq_zero_iff
#print axioms Goldbach.OffDiagonalCertificate.weight_eq_positivePart_sub_negativePart
#print axioms Goldbach.OffDiagonalCertificate.mod3SignedImbalance_pos_iff_negativeMass_lt_positiveMass
#print axioms Goldbach.OffDiagonalCertificate.intrinsicFavorableCore_eq_mod3PositiveMass_of_all_mem_window
#print axioms Goldbach.OffDiagonalCertificate.displacement_abs_lt_target_of_mem_of_even
#print axioms Goldbach.OffDiagonalCertificate.fixedP3_M2_all_displacements_mem_window_of_even
#print axioms Goldbach.OffDiagonalCertificate.fixedP3_M2_intrinsicCore_eq_mod3PositiveMass_of_even
#print axioms Goldbach.OffDiagonalCertificate.fixedP3_M2_negativeMass_lt_intrinsicCore_of_ge56_even_of_signedImbalance_pos
